name: Matrix

on:
  push:
    branches:
      - matrix

jobs:
  build:
    strategy:
      matrix:
        node_version: [12, 22, 23]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm test