# Demo using matrix to generate multiple jobs against combinations of input such as OS and language versions
name: Matrix

on:
  push:
    branches:
      - matrix

jobs:
  build:
    # Create parallel jobs for all these combinations of input
    strategy:
      matrix:
        node_version: [12, 22, 23]

    # Do not skip any jobs on failure
    continue-on-error: true

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}

      - name: Install dependencies
        run: npm ci

      - name: Unit tests
        run: npm test