# Demo calling another (reusable) workflow
name: Re-usable workflow consumer
on:
  push:
    branches:
      - reusable-workflow

jobs:
  caller:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: npm cache
        id: cache
        uses: actions/cache@v4.2.0
        with:
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          path: node_modules

      - name: Install code dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      # Call re-usable workflow which lists the files in the cache
      - name: Call re-usable workflow
        uses: ./.github/workflows/reusable-workflow.yml
        with:
          # cache-primary-key is available as an output with actions/cache/restore but not actions/cache
          cache_primary_key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}